#include<stdio.h>
#include<conio.h>
FILE *input,*output;
int local[10]={0},flag[10]={0},jumpaddr[10]={0};
char temp[0xffff][0xf],memory[0xffff]={0};
int main(){
	input=fopen("/sdcard/pfh/base/temp.asm","r");
	printf("%d\n",input);
	output=fopen("./disk.bin","w");
	for(local[0]=0;local[0]<0xffff;local[0]++)
		for(local[1]=0;local[1]<0xf;local[1]++)
			temp[local[0]][local[1]]=0;
	local[0]=0;local[1]=0;
	while(!feof(input)){
		local[0]=fgetc(input);
		if(local[0]==34){
			temp[local[1]][local[2]++]=local[0];
			while(1){
				local[0]=fgetc(input);
				temp[local[1]][local[2]++]=local[0];
				if(local[0]==34)
					break;
				if(local[2]>0xf){
					local[1]++;local[2]=0;
				}
			}
			continue;
		}
		if(local[0]==10||local[0]==32||local[0]==-1){
			local[1]++;local[2]=0;
		}else{
			temp[local[1]][local[2]++]=local[0];//ysb,
		}
	}
	local[1]=0;
	for(local[0]=0;local[0]<0x100;local[0]++){
		if(temp[local[0]][0]==0x30&&temp[local[0]][1]==0x78){
			local[2]=strtol(temp[local[0]],0,0);
			memory[local[1]++]=local[2];
			local[2]=0;
		}
		if(temp[local[0]][0]==0x22){
			while(1){
				memory[local[1]++]=temp[local[0]][++local[2]];
				if(temp[local[0]][local[2]+1]==0x22)
					break;
				else if(local[2]<0xf){
					local[0]++;local[2]=0;
				}
			}
		}
		if(strcmp(temp[local[0]],"add")==0)
			memory[local[1]++]=0x01;
		if(strcmp(temp[local[0]],"sub")==0)
			memory[local[1]++]=0x02;
		if(strcmp(temp[local[0]],"xadd")==0)
			memory[local[1]++]=0x03;
		if(strcmp(temp[local[0]],"xsub")==0)
			memory[local[1]++]=0x04;
		if(strcmp(temp[local[0]],"and")==0)
			memory[local[1]++]=0x11;
		if(strcmp(temp[local[0]],"or")==0)//蒙古牛奶一千块一斤
			memory[local[1]++]=0x12;
		if(strcmp(temp[local[0]],"not")==0)
			memory[local[1]++]=0x13;
		if(strcmp(temp[local[0]],"mov")==0)
			memory[local[1]++]=0x21;
		if(strcmp(temp[local[0]],"copy")==0)
			memory[local[1]++]=0x22;
		if(strcmp(temp[local[0]],"goto")==0)
			memory[local[1]++]=0x23;
		if(strcmp(temp[local[0]],"geta")==0)
			memory[local[1]++]=0x24;
		if(strcmp(temp[local[0]],">")==0)
			memory[local[1]++]=0x25;
		if(strcmp(temp[local[0]],"<")==0)
			memory[local[1]++]=0x26;
		if(strcmp(temp[local[0]],"=")==0)
			memory[local[1]++]=0x27;
		if(strcmp(temp[local[0]],"putc")==0)
			memory[local[1]++]=0x31;
		if(strcmp(temp[local[0]],"putn")==0)
			memory[local[1]++]=0x32;
		if(strcmp(temp[local[0]],"puth")==0)
			memory[local[1]++]=0x33;
		if(strcmp(temp[local[0]],"getc")==0)
			memory[local[1]++]=0x34;
		if(strcmp(temp[local[0]],"getn")==0)
			memory[local[1]++]=0x35;
		if(strcmp(temp[local[0]],"geth")==0)
			memory[local[1]++]=0x36;
	}
	for(local[0]=0;local[0]<0x100;local[0]++)
		printf("%x|%x\n",local[0],fputc(memory[local[0]],output));
}